---
server:
  shutdown: graceful
  port: ${PORT:8081}
  servlet:
    context-path: /insurance-policies
axon:
  axonserver:
    enabled: false
  serializer:
    general: jackson
spring:
  application.name: insurance-policies
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  liquibase:
    enabled: true
    change-log: classpath:db/db-changelog.xml
  datasource:
    #url: jdbc:postgresql://${DB_WRITER_HOST}:${DB_WRITER_PORT}/${DB_WRITER_DATABASE}
    url: jdbc:postgresql://localhost:5434/insurance-policies
    username: insurance-policies
    password: insurance-policies
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        check_nullability: true
        ddl-auto: update